apiVersion: apps/v1
kind: Deployment
metadata:
        name: mysql
        labels:
                app: mysql
spec:
        replicas: 1
        selector: 
                matchLabels: 
                        app: mysql
        template:
                metadata: 
                        labels: 
                                app: mysql
                spec:
                        containers:
                                - name: mysql
                                  image: mysql_custom:v1
                                  ports:
                                          - containerPort : 3306
                                  volumeMounts: 
                                          - mountPath: /var/lib/mysql/
                                            #- mountPath: /home/test
                                            name: var-lib-mysql
                                  livenessProbe:
                                            exec:
                                                    command:
                                                            - pgrep
                                                            - "mysqld"
                                            initialDelaySeconds: 5
                                            periodSeconds: 5
                        restartPolicy: Always
                        volumes:
                                - name: var-lib-mysql
                                  persistentVolumeClaim:
                                        claimName: mysql-pvc
