#kind: ClusterRole
#apiVersion: rbac.authorization.k8s.io/v1
#metadata: 
#    name: influx:cluster:viewer
#    labels: 
#        rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
#rules: 
#    - apiGroups: [""] 
#      #resources: ["nodes", "pods", "services", "statefulset", "persistent]
#      resources: [""]
#      verbs: ["get", "list", "watch"]
#
#---
#kind: ClusterRole
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#    name: influx:telegraf
#aggregationRule:
#    clusterRoleSelectors:
#        - matchLabels:
#            rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
#        - matchLabels:
#            rbac.authorization.k8s.io/aggregate-to-view: "true" 
#rules: [] # Rules are automatically filled in by the controller manager.
#---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: telegraf-account
    labels:
        app: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
    name: telegraf:viewer
subjects:
    - kind: ServiceAccount 
      name: telegraf-account
      namespace: default
roleRef: 
    kind: ClusterRole 
    apiGroup: rbac.authorization.k8s.io 
    name: cluster-admin
    #name: influx:telegraf
