apiVersion: v1
kind: Service
metadata:
        name: ftps-service
spec:
        type: LoadBalancer
        selector:
                app: ftps
        ports:
                - name : active-ftp
                  protocol: TCP
                  port: 21
                - name : passive-ftp
                  protocol: TCP
                  port: 20
