apiVersion: v1
kind: Service
metadata:
        name: phpmyadmin
spec:
        type: LoadBalancer
        selector:
                app: phpmyadmin
        ports:
                - name: http
                  protocol: TCP
                  port: 5000
                  targetPort: 8000
