apiVersion: v1
kind: Service
metadata:
        name: phpmyadmin
        annotations:
            metallb.universe.tf/allow-shared-ip: sharing key
spec:
        type: LoadBalancer
        loadBalancerIP: 172.17.0.200
        selector:
                app: phpmyadmin
        ports:
                - name: http
                  protocol: TCP
                  port: 5000
                  targetPort: 5000
