apiVersion: apps/v1
kind: Deployment
metadata:
        name: wordpress-deploy
        labels:
                app: wordpress
spec:
        replicas: 1
        selector: 
                matchLabels: 
                        app: wordpress
        template:
                metadata: 
                        labels: 
                                app: wordpress
                spec:
                        containers:
                                - name: wordpress
                                  image: wordpress_custom:v1
                                  ports:
                                          - containerPort : 80
