apiVersion: v1
kind: Service
metadata:
        name: wordpress
spec:
        type: LoadBalancer
        selector:
                app: wordpress
        ports:
                - name: http
                  protocol: TCP
                  port: 5050
                  targetPort: 80
