{
 "title": "ft_services",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "show tag values with key = \"container_name\""
   },
   {
    "name": "host",
    "query": "show tag values with key = \"engine_host\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "# **Engine Host Infos**" },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total memory capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Containers count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Images count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "File descriptors count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_used_file_descriptors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": { "content": "# **Container Infos**" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instant CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "cpu_usage (%)",
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^${container}$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "memory usage (bytes)",
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=", "value": "minikube" }
     ]
    },
    {
     "alias": "memory limit (bytes)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  }
 ]
}