apiVersion: v1
kind: ConfigMap
metadata:
    name: telegraf-config
data:
    telegraf.conf: |+
        [[outputs.influxdb]]
        urls = ["$INFLUXDB_URL"]
        database = "$INFLUXDB_DB"
        username = "$INFLUXDB_USER"
        password = "$INFLUXDB_USER_PASSWORD"

        [[inputs.kube_inventory]]
        url = "https://kubernetes"
        insecure_skip_verify = true
        response_timeout="20s"
        #namespace = ""
        #bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"

        selector_include = []
        selector_exclude = ["*"]

        #[[inputs.kubernetes]]

        #url = "http://127.0.0.1:10250"
        #insecure_skip_verify = true
