apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf
spec:
    selector:
        matchLabels:
            app: telegraf
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: telegraf
        spec:
            serviceAccountName: telegraf-account
            containers:
                - image: telegraf_custom:v1
                  name: telegraf
                  envFrom:
                      - secretRef:
                          name: telegraf-secrets
                  volumeMounts:
                      - name: telegraf-config-volume
                        mountPath: /etc/telegraf.conf
                        subPath: telegraf.conf
                        readOnly: true
            volumes:
                - name: telegraf-config-volume
                  configMap:
                    name: telegraf-config
